import type {
  LGUMapMarker,
  PromiseStats,
  PromiseItem,
  DashboardData,
  BudgetSummary,
  CommunityReport,
  Project,
} from '@/types/models';

// Real Philippine LGU coordinates for map markers
export const MOCK_MAP_MARKERS: LGUMapMarker[] = [
  { id: 1, name: 'Quezon City', lat: 14.6760, lng: 121.0437, score: 72.5, type: 'city' },
  { id: 2, name: 'Manila', lat: 14.5995, lng: 120.9842, score: 65.0, type: 'city' },
  { id: 3, name: 'Cebu City', lat: 10.3157, lng: 123.8854, score: 81.2, type: 'city' },
  { id: 4, name: 'Davao City', lat: 7.1907, lng: 125.4553, score: 78.3, type: 'city' },
  { id: 5, name: 'Makati', lat: 14.5547, lng: 121.0244, score: 85.1, type: 'city' },
  { id: 6, name: 'Pasig', lat: 14.5764, lng: 121.0851, score: 69.8, type: 'city' },
  { id: 7, name: 'Taguig', lat: 14.5176, lng: 121.0509, score: 74.6, type: 'city' },
  { id: 8, name: 'Caloocan', lat: 14.6488, lng: 120.9685, score: 58.2, type: 'city' },
  { id: 9, name: 'Zamboanga City', lat: 6.9214, lng: 122.0790, score: 62.4, type: 'city' },
  { id: 10, name: 'Baguio', lat: 16.4023, lng: 120.5960, score: 76.9, type: 'city' },
  { id: 11, name: 'Iloilo City', lat: 10.7202, lng: 122.5621, score: 79.3, type: 'city' },
  { id: 12, name: 'Cagayan de Oro', lat: 8.4542, lng: 124.6319, score: 71.5, type: 'city' },
  { id: 13, name: 'General Santos', lat: 6.1164, lng: 125.1716, score: 67.8, type: 'city' },
  { id: 14, name: 'Antipolo', lat: 14.5886, lng: 121.1762, score: 63.4, type: 'city' },
  { id: 15, name: 'Bacoor', lat: 14.4624, lng: 120.9645, score: 59.1, type: 'city' },
  { id: 16, name: 'San Jose del Monte', lat: 14.8139, lng: 121.0453, score: 55.7, type: 'city' },
  { id: 17, name: 'Mandaue', lat: 10.3236, lng: 123.9223, score: 73.2, type: 'city' },
  { id: 18, name: 'Butuan', lat: 8.9475, lng: 125.5406, score: 68.5, type: 'city' },
  { id: 19, name: 'Naga', lat: 13.6218, lng: 123.1948, score: 82.7, type: 'city' },
  { id: 20, name: 'Puerto Princesa', lat: 9.7392, lng: 118.7353, score: 70.3, type: 'city' },
  { id: 21, name: 'Tacloban', lat: 11.2543, lng: 124.9556, score: 64.1, type: 'city' },
  { id: 22, name: 'Legazpi', lat: 13.1391, lng: 123.7438, score: 66.9, type: 'city' },
  { id: 23, name: 'Olongapo', lat: 14.8292, lng: 120.2828, score: 75.4, type: 'city' },
  { id: 24, name: 'Laoag', lat: 18.1978, lng: 120.5937, score: 61.8, type: 'city' },
  { id: 25, name: 'Tuguegarao', lat: 17.6132, lng: 121.7270, score: 57.3, type: 'city' },
];

export const MOCK_PROMISE_STATS: PromiseStats = {
  lgu_id: 1,
  total: 47,
  counts: {
    kept: 12,
    broken: 8,
    in_progress: 15,
    pending: 7,
    partially_kept: 3,
    unverifiable: 2,
  },
  percentages: {
    kept: 25.5,
    broken: 17.0,
    in_progress: 31.9,
    pending: 14.9,
    partially_kept: 6.4,
    unverifiable: 4.3,
  },
};

export const MOCK_PROMISES: PromiseItem[] = [
  {
    id: 1, official_id: 1, lgu_id: 1,
    title: 'Build 5 new public schools in District 1',
    description: 'Construction of 5 elementary schools to address classroom shortage.',
    category: 'Education', status: 'in_progress',
    evidence_summary: '2 schools completed, 3 under construction',
    date_promised: '2025-06-15', deadline: '2027-12-31',
    verified_at: '2026-02-01', verified_by: 'COA Audit Report 2025',
    confidence_score: 0.85,
  },
  {
    id: 2, official_id: 1, lgu_id: 1,
    title: 'Free wi-fi in all public parks',
    description: null, category: 'Technology', status: 'kept',
    evidence_summary: 'Wi-fi installed in 12 out of 12 parks',
    date_promised: '2025-01-10', deadline: '2025-12-31',
    verified_at: '2025-11-20', verified_by: 'Field verification',
    confidence_score: 0.95,
  },
  {
    id: 3, official_id: 1, lgu_id: 1,
    title: 'Reduce crime rate by 30%',
    description: null, category: 'Public Safety', status: 'broken',
    evidence_summary: 'Crime rate decreased by only 8%',
    date_promised: '2025-01-10', deadline: '2026-06-30',
    verified_at: '2026-03-01', verified_by: 'PNP Statistics Report',
    confidence_score: 0.72,
  },
  {
    id: 4, official_id: 2, lgu_id: 1,
    title: 'Complete flood control project in Barangay 42',
    description: null, category: 'Infrastructure', status: 'pending',
    evidence_summary: null,
    date_promised: '2025-07-01', deadline: '2027-06-30',
    verified_at: null, verified_by: null,
    confidence_score: null,
  },
  {
    id: 5, official_id: 1, lgu_id: 1,
    title: 'Plant 10,000 trees along major roads',
    description: null, category: 'Environment', status: 'partially_kept',
    evidence_summary: '6,200 trees planted as of last count',
    date_promised: '2025-03-22', deadline: '2026-12-31',
    verified_at: '2026-02-15', verified_by: 'DENR Report',
    confidence_score: 0.62,
  },
];

export const MOCK_BUDGET_SUMMARY: BudgetSummary[] = [
  { category: 'Infrastructure', allocated: 850000000, released: 720000000, utilized: 580000000 },
  { category: 'Education', allocated: 420000000, released: 400000000, utilized: 380000000 },
  { category: 'Health', allocated: 350000000, released: 330000000, utilized: 290000000 },
  { category: 'Social Services', allocated: 280000000, released: 250000000, utilized: 210000000 },
  { category: 'Environment', allocated: 120000000, released: 100000000, utilized: 75000000 },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 1, lgu_id: 1,
    title: 'Quezon Avenue Road Widening Project',
    description: 'Four-lane road widening and resurfacing of Quezon Avenue from Elliptical Road to East Avenue, including drainage improvements and pedestrian sidewalks.',
    category: 'Infrastructure', status: 'ongoing',
    contractor: 'DMCI Holdings, Inc.',
    approved_budget: 285000000, contract_amount: 272000000, actual_cost: null,
    start_date: '2025-08-15', target_end_date: '2026-12-31', actual_end_date: null,
    latitude: 14.6510, longitude: 121.0390, address: 'Quezon Avenue, Quezon City',
    philgeps_ref: 'QC-2025-INF-0142', fiscal_year: 2025,
  },
  {
    id: 2, lgu_id: 1,
    title: 'Barangay Health Center - Batasan Hills',
    description: 'Construction of a two-storey barangay health center with birthing facility, pharmacy, and telemedicine room to serve the Batasan Hills community.',
    category: 'Health', status: 'completed',
    contractor: 'Hilmarc\'s Construction Corp.',
    approved_budget: 45000000, contract_amount: 42500000, actual_cost: 41800000,
    start_date: '2025-02-01', target_end_date: '2025-11-30', actual_end_date: '2025-10-15',
    latitude: 14.6868, longitude: 121.0963, address: 'Batasan Hills, Quezon City',
    philgeps_ref: 'QC-2025-HLT-0028', fiscal_year: 2025,
  },
  {
    id: 3, lgu_id: 1,
    title: 'Payatas Elementary School Building',
    description: 'Construction of a three-storey, 12-classroom school building with science laboratory and computer room to address classroom shortage in Payatas area.',
    category: 'Education', status: 'ongoing',
    contractor: 'EEI Corporation',
    approved_budget: 68000000, contract_amount: 65200000, actual_cost: null,
    start_date: '2025-06-01', target_end_date: '2026-08-31', actual_end_date: null,
    latitude: 14.7090, longitude: 121.1050, address: 'Payatas, Quezon City',
    philgeps_ref: 'QC-2025-EDU-0056', fiscal_year: 2025,
  },
  {
    id: 4, lgu_id: 1,
    title: 'Tullahan River Flood Control System',
    description: 'Installation of pumping stations and construction of floodwalls along a 2.5 km stretch of Tullahan River to mitigate flooding in low-lying barangays.',
    category: 'Infrastructure', status: 'delayed',
    contractor: 'Megawide Construction Corp.',
    approved_budget: 520000000, contract_amount: 498000000, actual_cost: null,
    start_date: '2025-03-01', target_end_date: '2026-06-30', actual_end_date: null,
    latitude: 14.6700, longitude: 121.0000, address: 'Tullahan River, Quezon City',
    philgeps_ref: 'QC-2025-INF-0089', fiscal_year: 2025,
  },
  {
    id: 5, lgu_id: 1,
    title: 'Novaliches Water District Pipeline Extension',
    description: 'Laying of 8 km of new water distribution pipelines to serve previously unserved households in the Novaliches area, including pump station upgrades.',
    category: 'Water & Sanitation', status: 'bidding',
    contractor: null,
    approved_budget: 180000000, contract_amount: null, actual_cost: null,
    start_date: null, target_end_date: '2027-03-31', actual_end_date: null,
    latitude: 14.7300, longitude: 121.0440, address: 'Novaliches, Quezon City',
    philgeps_ref: 'QC-2026-WTR-0012', fiscal_year: 2026,
  },
  {
    id: 6, lgu_id: 1,
    title: 'Solar Panel Installation - City Hall Complex',
    description: 'Installation of 500 kW solar panel system across City Hall rooftops and parking structures to reduce electricity costs and carbon footprint.',
    category: 'Environment', status: 'planned',
    contractor: null,
    approved_budget: 35000000, contract_amount: null, actual_cost: null,
    start_date: null, target_end_date: '2027-06-30', actual_end_date: null,
    latitude: 14.6476, longitude: 121.0508, address: 'Quezon City Hall, Quezon City',
    philgeps_ref: null, fiscal_year: 2026,
  },
  {
    id: 7, lgu_id: 1,
    title: 'Multi-Purpose Evacuation Center - Bagong Silangan',
    description: 'Construction of a typhoon-resilient evacuation center with 500-person capacity, kitchen facilities, medical station, and emergency power supply.',
    category: 'Social Services', status: 'ongoing',
    contractor: 'First Balfour, Inc.',
    approved_budget: 92000000, contract_amount: 88500000, actual_cost: null,
    start_date: '2025-09-01', target_end_date: '2026-09-30', actual_end_date: null,
    latitude: 14.6950, longitude: 121.1100, address: 'Bagong Silangan, Quezon City',
    philgeps_ref: 'QC-2025-SOC-0034', fiscal_year: 2025,
  },
  {
    id: 8, lgu_id: 1,
    title: 'CCTV and Public Safety Network Expansion',
    description: 'Installation of 250 additional CCTV cameras at major intersections and public spaces, with fiber-optic connectivity to the city command center.',
    category: 'Public Safety', status: 'completed',
    contractor: 'Globe Telecom, Inc.',
    approved_budget: 125000000, contract_amount: 118000000, actual_cost: 115500000,
    start_date: '2025-01-15', target_end_date: '2025-09-30', actual_end_date: '2025-09-22',
    latitude: 14.6488, longitude: 121.0509, address: 'Various Locations, Quezon City',
    philgeps_ref: 'QC-2025-SAF-0011', fiscal_year: 2025,
  },
  {
    id: 9, lgu_id: 1,
    title: 'La Mesa Eco Park Rehabilitation',
    description: 'Rehabilitation of park facilities including new jogging trails, playground equipment, picnic areas, and native tree planting of 5,000 seedlings.',
    category: 'Environment', status: 'ongoing',
    contractor: 'Manila Waterworks & Sewerage System',
    approved_budget: 58000000, contract_amount: 55000000, actual_cost: null,
    start_date: '2025-11-01', target_end_date: '2026-11-30', actual_end_date: null,
    latitude: 14.6800, longitude: 121.0700, address: 'La Mesa Eco Park, Quezon City',
    philgeps_ref: 'QC-2025-ENV-0019', fiscal_year: 2025,
  },
  {
    id: 10, lgu_id: 1,
    title: 'Public Market Modernization - Balintawak',
    description: 'Demolition and reconstruction of the Balintawak public market with modern ventilation, fire suppression systems, and sanitary facilities for 300 vendor stalls.',
    category: 'Infrastructure', status: 'delayed',
    contractor: 'Sta. Elena Construction & Development Corp.',
    approved_budget: 310000000, contract_amount: 295000000, actual_cost: null,
    start_date: '2025-04-01', target_end_date: '2026-10-31', actual_end_date: null,
    latitude: 14.6570, longitude: 121.0020, address: 'Balintawak, Quezon City',
    philgeps_ref: 'QC-2025-INF-0067', fiscal_year: 2025,
  },
];

export const MOCK_REPORTS: CommunityReport[] = [
  {
    id: 1, user_id: 12, lgu_id: 1, project_id: 1,
    title: 'Road widening causing severe traffic on Quezon Avenue',
    description: 'The ongoing road widening project on Quezon Avenue has caused severe traffic congestion during rush hours. Vehicles are stuck for over an hour in what used to be a 15-minute drive. There seems to be no proper traffic management plan in place.',
    report_type: 'concern', status: 'under_review',
    latitude: 14.6510, longitude: 121.0390,
    address: 'Quezon Avenue, Quezon City',
    upvote_count: 47, is_anonymous: false,
    created_at: '2026-03-20T14:30:00Z',
  },
  {
    id: 2, user_id: null, lgu_id: 1, project_id: 4,
    title: 'Suspiciously high cost for flood control materials',
    description: 'I work near the Tullahan River project site and noticed that the materials being used look substandard. The concrete pipes appear thinner than standard specifications. The project cost seems inflated based on what is actually being installed.',
    report_type: 'corruption_tip', status: 'submitted',
    latitude: 14.6700, longitude: 121.0000,
    address: 'Tullahan River, Quezon City',
    upvote_count: 83, is_anonymous: true,
    created_at: '2026-03-18T09:15:00Z',
  },
  {
    id: 3, user_id: 8, lgu_id: 1, project_id: 2,
    title: 'Batasan Hills Health Center now operational',
    description: 'Happy to report that the new barangay health center in Batasan Hills is now fully operational. They offer free checkups every Monday and Wednesday. The birthing facility has already served several mothers in the community.',
    report_type: 'progress_update', status: 'verified',
    latitude: 14.6868, longitude: 121.0963,
    address: 'Batasan Hills, Quezon City',
    upvote_count: 124, is_anonymous: false,
    created_at: '2026-03-15T11:00:00Z',
  },
  {
    id: 4, user_id: 22, lgu_id: 1, project_id: 10,
    title: 'Balintawak Market vendors displaced with no relocation',
    description: 'Over 100 vendors have been displaced by the market modernization project but many still have not received their promised temporary relocation stalls. Some are now selling on the sidewalk with no protection from rain.',
    report_type: 'concern', status: 'under_review',
    latitude: 14.6570, longitude: 121.0020,
    address: 'Balintawak, Quezon City',
    upvote_count: 65, is_anonymous: false,
    created_at: '2026-03-12T16:45:00Z',
  },
  {
    id: 5, user_id: null, lgu_id: 1, project_id: 4,
    title: 'Tullahan River project 6 months behind schedule',
    description: 'The flood control project along Tullahan River was supposed to be halfway done by now but construction has barely progressed. The site has been idle for weeks. Rainy season is approaching and residents are worried about flooding again.',
    report_type: 'delay_report', status: 'verified',
    latitude: 14.6700, longitude: 121.0000,
    address: 'Tullahan River, Quezon City',
    upvote_count: 91, is_anonymous: true,
    created_at: '2026-03-10T08:20:00Z',
  },
  {
    id: 6, user_id: 15, lgu_id: 1, project_id: 3,
    title: 'Payatas school construction going well',
    description: 'The new school building in Payatas is progressing nicely. The second floor is already being constructed. Workers are on-site every day. This will be a big help for the children in our area who currently have to travel far for school.',
    report_type: 'progress_update', status: 'verified',
    latitude: 14.7090, longitude: 121.1050,
    address: 'Payatas, Quezon City',
    upvote_count: 38, is_anonymous: false,
    created_at: '2026-03-08T13:10:00Z',
  },
  {
    id: 7, user_id: null, lgu_id: 1, project_id: 8,
    title: 'Many CCTV cameras already not working',
    description: 'Several of the newly installed CCTV cameras along Commonwealth Avenue are already not functioning. At least 5 cameras near our barangay have been dark for over a month. This defeats the purpose of the public safety investment.',
    report_type: 'concern', status: 'submitted',
    latitude: 14.6488, longitude: 121.0509,
    address: 'Commonwealth Avenue, Quezon City',
    upvote_count: 52, is_anonymous: true,
    created_at: '2026-03-05T10:30:00Z',
  },
  {
    id: 8, user_id: 30, lgu_id: 1, project_id: 9,
    title: 'La Mesa Eco Park trails are excellent',
    description: 'The rehabilitated jogging trails at La Mesa Eco Park are fantastic. Well-paved, properly lit, and the new native trees provide great shade. A wonderful improvement for the community. Thank you to the project team.',
    report_type: 'feedback', status: 'verified',
    latitude: 14.6800, longitude: 121.0700,
    address: 'La Mesa Eco Park, Quezon City',
    upvote_count: 76, is_anonymous: false,
    created_at: '2026-03-02T15:50:00Z',
  },
];

export const MOCK_DASHBOARD: DashboardData = {
  lgu: { id: 1, name: 'Quezon City', transparency_score: 72.5 },
  budget: { total_allocated: 2020000000, total_utilized: 1535000000 },
  total_projects: 142,
  promises: {
    kept: 12, broken: 8, in_progress: 15,
    pending: 7, partially_kept: 3, unverifiable: 2,
  },
  total_reports: 89,
};
